"""KAI2 regression guard matrix."""
from __future__ import annotations

CLOSURE_MATRIX = {
    "KAI2-001": ("pyproject.toml", "pytest>=9.0.3"),
    "KAI2-002": ("tests/unit/test_init_v02.py", "test_init_indexes_seed_concepts_in_wiki_index"),
    "KAI2-003": ("tests/unit/test_cli_v02.py", "test_run_json_stdout_is_parseable"),
    "KAI2-004": ("tests/unit/test_cli_v02.py", "test_run_json_dry_stdout_is_parseable"),
    "KAI2-005": ("tests/unit/test_cli_v02.py", "test_lint_honors_stale_after_days_config"),
    "KAI2-006": ("tests/unit/test_cli_v02.py", "test_feedback_unknown_run_id_is_user_friendly"),
    "KAI2-007": ("tests/unit/test_config.py", "auto_save_query_answers"),
    "KAI2-008": ("tests/unit/test_runner_abc.py", "test_plugin_entry_points_are_not_loaded_without_opt_in"),
    "KAI2-009": ("tests/unit/test_runner_abc.py", "test_dispatch_rejects_non_runner_registry_object"),
    "KAI2-010": ("tests/unit/test_runner_abc.py", "test_dispatch_honors_runner_applicable"),
    "KAI2-011": ("tests/unit/test_mcp_client.py", "test_stub_reads_bom_prefixed_canned_response"),
    "KAI2-012": ("tests/unit/test_config.py", "KAI2-012"),
    "KAI2-013": ("tests/unit/test_config.py", 'backend = "STUB"'),
    "KAI2-014": ("src/kairos/cli.py", "ingested:"),
    "KAI2-015": ("src/kairos/cli.py", "rich_markup_mode=None"),
    "KAI2-016": ("tests/unit/test_cli_v02.py", "no findings"),
    "KAI2-017": ("src/kairos/memory/wiki_index.py", "PRAGMA foreign_keys = ON"),
    "KAI2-018": ("src/kairos/wiki/init.py", "remove_page"),
    "KAI2-019": ("src/kairos/memory/wiki_index.py", "normalize_wikilink"),
    "KAI2-020": ("src/kairos/runners/base.py", "time.perf_counter"),
    "KAI2-021": ("tests/unit/test_cli_v02.py", "json.loads"),
    "KAI2-022": ("tests/unit/test_runner_abc.py", "entry_points"),
    "KAI2-023": ("tests/unit/test_config.py", "source_paths"),
    "KAI2-024": ("tests/integration/test_mcp_server.py", "raw_path"),
    "KAI2-025": ("src/kairos/cli.py", "def history"),
    "KAI2-026": ("tests/unit/test_v02_misc.py", "WikiPaths"),
    "KAI2-027": (".github/workflows/ci.yml", "uv run bandit -ll -r src/"),
    "KAI2-028": ("tests/unit/test_v02_misc.py", "test_kairos_db_home_redirects_db"),
    "KAI2-029": ("src/kairos/cli.py", "def list_feedback"),
    "KAI2-030": ("src/kairos/wiki/query.py", "wiki_index"),
}
